# Generated by Django 2.0.1 on 2018-01-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_openehr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='addressdetails',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='demographicpersonal',
            options={'verbose_name_plural': 'Personal Demographics'},
        ),
        migrations.RenameField(
            model_name='identifier',
            old_name='demographics',
            new_name='demographic_personal',
        ),
        migrations.AddField(
            model_name='bodysite',
            name='body_site_name',
            field=models.CharField(blank=True, help_text='The identifier of the body site, using a terminology where possible', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personname',
            name='demographic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_openehr.DemographicPersonal'),
        ),
    ]
