# Generated by Django 2.0.1 on 2018-02-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_openehr', '0004_auto_20180131_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='InpatientAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_admission', models.DateTimeField(blank=True, null=True)),
                ('admission_method', models.CharField(blank=True, help_text='How the patient was admitted to hospital', max_length=255, null=True)),
                ('source_of_admission', models.CharField(blank=True, help_text='The locaton of the patient immediately prior to admission', max_length=255, null=True)),
                ('referrer_details', models.ManyToManyField(blank=True, to='django_openehr.DemographicProfessional')),
            ],
        ),
        migrations.CreateModel(
            name='ReasonForEncounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(blank=True, help_text='Identification of the type, or administrative category, of healthcare sought or required by the subject of care.', max_length=255, null=True)),
                ('presenting_problem', models.CharField(blank=True, help_text='Identification of the clinical or social problem motivating the subject of care to seeking healthcare.', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reasons for Encounter',
            },
        ),
        migrations.AlterField(
            model_name='relevantcontact',
            name='person_name',
            field=models.ManyToManyField(blank=True, to='django_openehr.PersonName'),
        ),
        migrations.AlterField(
            model_name='relevantcontact',
            name='telecom_details',
            field=models.ManyToManyField(blank=True, to='django_openehr.TelecomDetails'),
        ),
    ]
