# Generated by Django 2.0.1 on 2018-01-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(choices=[('REGISTERED', 'Registered name [The name by which the subject is officially registered.]'), ('PREVIOUS', 'Previous name [Name previously used by this person.]'), ('BIRTH', 'Birth name [Name given to this person at birth.]'), ('AKA', 'AKA [Person also known as.]'), ('ALIAS', 'Alias [Other name used by this person.]'), ('MAIDEN', 'Maiden Name [Name used by this persion before marriage.]'), ('PROFESSIONAL', 'Professional name [The name used by the subject for business or professional purposes.]'), ('REPORTING', 'Reporting name [The subject’s name as it is to be used for reporting, when used with a specific identifier.]')], max_length=200)),
                ('preferred_name', models.BooleanField()),
                ('unstructured_name', models.CharField(max_length=200)),
                ('title', models.CharField(choices=[('DR', 'Dr.'), ('MRS', 'Mrs.'), ('MR', 'Mr.'), ('MISS', 'Miss'), ('MS', 'Ms.'), ('PROF', 'Prof.'), ('SIR', 'Sir'), ('REV', 'Rev')], max_length=20)),
                ('given_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('family_name', models.CharField(max_length=200)),
                ('suffix', models.CharField(max_length=20)),
                ('relationship_to_subject', models.CharField(max_length=200)),
            ],
        ),
    ]
